name: develop CI_CD
on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]
jobs:
  develop_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # Puedes cambiar la versión según tu proyecto
          distribution: 'adopt' # O 'zulu', 'temurin', etc., según lo que prefieras

      - name: Build with Maven
        run: mvn install # O 'mvn package' si solo quieres empaquetar

      - name: Run tests
        run: mvn test # Esto ejecutará tus pruebas JUnit
