name: develop CI_CD
on: 
  push:
    branches: [ "develop"]
  pull_request:
    branches: [ "develop"]
jobs:
  develop_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11' # O la versión que necesites
          distribution: 'adopt'

      - name: Compile Java code
        run: |
          find src -name "*.java" > sources.txt
          javac -cp .:junit-4.13.2.jar -d out @sources.txt

      - name: Run tests
        run: |
          java -cp .:junit-4.13.2.jar:out org.junit.runner.JUnitCore your.package.name.YourTestClass
