name: release_ci_cd
on: 
  push:
    branches: [ "release"]
  pull_request:
    branches: [ "release"]
jobs:
  release_ci_cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
